"""add sell logic and background tasks

Revision ID: 23805777d53a
Revises:
Create Date: 2026-05-11 01:34:32.255190

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23805777d53a"
down_revision = "ca104efdddb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    existing_bp_cols = []
    try:
        existing_bp_cols = [c["name"] for c in inspector.get_columns("bond_portfolio")]
    except Exception:
        pass

    with op.batch_alter_table("bond_portfolio", schema=None) as batch_op:
        if "is_sold" not in existing_bp_cols:
            batch_op.add_column(sa.Column("is_sold", sa.Boolean(), nullable=True))
        if "sell_price" not in existing_bp_cols:
            batch_op.add_column(sa.Column("sell_price", sa.Float(), nullable=True))
        if "sell_date" not in existing_bp_cols:
            batch_op.add_column(sa.Column("sell_date", sa.Date(), nullable=True))
        if "realized_profit" not in existing_bp_cols:
            batch_op.add_column(sa.Column("realized_profit", sa.Float(), nullable=True))
        if "last_price" not in existing_bp_cols:
            batch_op.add_column(sa.Column("last_price", sa.Float(), nullable=True))
        if "last_updated" not in existing_bp_cols:
            batch_op.add_column(sa.Column("last_updated", sa.DateTime(), nullable=True))
        
        # Safe alter purchase_date (always safe to run or skip if matching)
        try:
            batch_op.alter_column("purchase_date", existing_type=sa.DATE(), nullable=False)
        except Exception:
            pass

        # Safe create foreign key
        try:
            batch_op.create_foreign_key("fk_bond_portfolio_users", "users", ["user_id"], ["id"])
        except Exception:
            pass

    with op.batch_alter_table("users", schema=None) as batch_op:
        try:
            batch_op.alter_column(
                "username",
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=80),
                existing_nullable=False,
            )
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=80),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    with op.batch_alter_table("bond_portfolio", schema=None) as batch_op:
        batch_op.drop_constraint("fk_bond_portfolio_users", type_="foreignkey")
        batch_op.alter_column("purchase_date", existing_type=sa.DATE(), nullable=True)
        batch_op.drop_column("last_updated")
        batch_op.drop_column("last_price")
        batch_op.drop_column("realized_profit")
        batch_op.drop_column("sell_date")
        batch_op.drop_column("sell_price")
        batch_op.drop_column("is_sold")

    # ### end Alembic commands ###
