"""initial schema

Revision ID: ca104efdddb2
Revises:
Create Date: 2026-05-22 13:47:19.549179

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca104efdddb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("email_notifications", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "visit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bond_portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("secid", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("buy_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("is_sold", sa.Boolean(), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sell_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sell_date", sa.Date(), nullable=True),
        sa.Column(
            "broker_commission", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bond_portfolio", schema=None) as batch_op:
        batch_op.create_index("ix_bp_is_sold", ["is_sold"], unique=False)
        batch_op.create_index("ix_bp_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_bp_user_sold", ["user_id", "is_sold"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("tx_type", sa.String(length=4), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("commission", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("tx_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("ix_tx_user_id", ["user_id"], unique=False)

    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("secid", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("added_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "isin", name="uq_watchlist_user_isin"),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index("ix_wl_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index("ix_wl_user_id")

    op.drop_table("watchlist")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_tx_user_id")

    op.drop_table("transactions")
    with op.batch_alter_table("bond_portfolio", schema=None) as batch_op:
        batch_op.drop_index("ix_bp_user_sold")
        batch_op.drop_index("ix_bp_user_id")
        batch_op.drop_index("ix_bp_is_sold")

    op.drop_table("bond_portfolio")
    op.drop_table("visit")
    op.drop_table("users")
    # ### end Alembic commands ###
